apiVersion: v1
kind: Service
metadata:
 name: gitea-nodeport
 namespace: gitea
spec:
 type: NodePort
 ports:
 - targetPort: 3000
   port: 3000
 selector:
  app: gitea
---
apiVersion: v1
kind: Service
metadata:
 name: gitea-lb
 namespace: gitea
spec:
 type: LoadBalancer
 ports:
 - targetPort: 3000
   port: 3000
 selector:
  app: gitea
